# max 'scale_w': 10
# max 'scale_h': 8

REGIONS = [
    {
        'name': '安徽省',
        'name_en': 'Anhui',
        'scale_w': 7.26,
        'scale_h': 8,
        'cities': [
            {
                'name': '安庆市',
                'name_en': 'Anqing',
                'scale_w': 8.02,
                'scale_h': 8,
            }, {
                'name': '蚌埠市',
                'name_en': 'Bengbu',
                'scale_w': 10,
                'scale_h': 5.84,
            }, {
                'name': '亳州市',
                'name_en': 'Bozhou',
                'scale_w': 8.4,
                'scale_h': 8,
            }, {
                'name': '池州市',
                'name_en': 'Chizhou',
                'scale_w': 9.28,
                'scale_h': 8,
            }, {
                'name': '滁州市',
                'name_en': 'Chuzhou',
                'scale_w': 10,
                'scale_h': 6.64,
            }, {
                'name': '阜阳市',
                'name_en': 'Fuyang',
                'scale_w': 10,
                'scale_h': 6.76,
            }, {
                'name': '合肥市',
                'name_en': 'Hefei',
                'scale_w': 6.46,
                'scale_h': 8,
            }, {
                'name': '淮北市',
                'name_en': 'Huaibei',
                'scale_w': 5.42,
                'scale_h': 8,
            }, {
                'name': '淮南市',
                'name_en': 'Huainan',
                'scale_w': 6.16,
                'scale_h': 8,
            }, {
                'name': '黄山市',
                'name_en': 'Huangshan',
                'scale_w': 10,
                'scale_h': 6.62,
            }, {
                'name': '六安市',
                'name_en': 'Liuan',
                'scale_w': 9.44,
                'scale_h': 8,
            }, {
                'name': '马鞍山市',
                'name_en': 'Maanshan',
                'scale_w': 10,
                'scale_h': 7.84,
            }, {
                'name': '宿州市',
                'name_en': 'Suzhou',
                'scale_w': 10,
                'scale_h': 6.8,
            }, {
                'name': '铜陵市',
                'name_en': 'Tongling',
                'scale_w': 10,
                'scale_h': 4.14,
            }, {
                'name': '芜湖市',
                'name_en': 'Wuhu',
                'scale_w': 10,
                'scale_h': 7.18,
            }, {
                'name': '宣城市',
                'name_en': 'Xuancheng',
                'scale_w': 9.82,
                'scale_h': 8,
          },
        ],
    }, {
        'name': '北京市',
        'name_en': 'Beijing',
        'scale_w': 7.92,
        'scale_h': 8,
        'cities': [
            {
                'name': '北京市',
                'name_en': 'Beijing',
                'scale_w': 7.92,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '重庆市',
        'name_en': 'Chongqing',
        'scale_w': 9.72,
        'scale_h': 8,
        'cities': [
          {
              'name': '重庆市',
              'name_en': 'Chongqing',
              'scale_w': 9.72,
              'scale_h': 8,
          },
        ],
    }, {
        'name': '福建省',
        'name_en': 'Fujian',
        'scale_w': 8.22,
        'scale_h': 8,
        'cities': [
            {
                'name': '福州市',
                'name_en': 'Fuzhou',
                'scale_w': 10,
                'scale_h': 6.32,
            }, {
                'name': '龙岩市',
                'name_en': 'Longyan',
                'scale_w': 9.12,
                'scale_h': 8,
            }, {
                'name': '南平市',
                'name_en': 'Nanping',
                'scale_w': 8.8,
                'scale_h': 8,
            }, {
                'name': '宁德市',
                'name_en': 'Ningde',
                'scale_w': 10,
                'scale_h': 6.44,
            }, {
                'name': '莆田市',
                'name_en': 'Putian',
                'scale_w': 10,
                'scale_h': 6.22,
            }, {
                'name': '泉州市',
                'name_en': 'Quanzhou',
                'scale_w': 7.68,
                'scale_h': 8,
            }, {
                'name': '三明市',
                'name_en': 'Sanming',
                'scale_w': 10,
                'scale_h': 7.22,
            }, {
                'name': '厦门市',
                'name_en': 'Xiamen',
                'scale_w': 8.48,
                'scale_h': 8,
            }, {
                'name': '漳州市',
                'name_en': 'Zhangzhou',
                'scale_w': 6.14,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '甘肃省',
        'name_en': 'Gansu',
        'scale_w': 10,
        'scale_h': 6.24,
        'cities': [
            {
                'name': '白银市',
                'name_en': 'Baiyin',
                'scale_w': 7.16,
                'scale_h': 8,
            }, {
                'name': '定西市',
                'name_en': 'Dingxi',
                'scale_w': 9.1,
                'scale_h': 8,
            }, {
                'name': '甘南藏族自治州',
                'name_en': 'Gannanzangzu',
                'scale_w': 10,
                'scale_h': 6.22,
            }, {
                'name': '嘉峪关市',
                'name_en': 'Jiayuguan',
                'scale_w': 10,
                'scale_h': 5.22,
                'disable_drill_down': True,
            }, {
                'name': '金昌市',
                'name_en': 'Jinchang',
                'scale_w': 10,
                'scale_h': 6.98,
            }, {
                'name': '酒泉市',
                'name_en': 'Jiuquan',
                'scale_w': 10,
                'scale_h': 5.9,
            }, {
                'name': '兰州市',
                'name_en': 'Lanzhou',
                'scale_w': 10,
                'scale_h': 7.58,
            }, {
                'name': '临夏回族自治州',
                'name_en': 'Linxiahuizu',
                'scale_w': 7.14,
                'scale_h': 8,
            }, {
                'name': '陇南市',
                'name_en': 'Longnan',
                'scale_w': 10,
                'scale_h': 7.58,
            }, {
                'name': '平凉市',
                'name_en': 'Pingliang',
                'scale_w': 10,
                'scale_h': 3.48,
            }, {
                'name': '庆阳市',
                'name_en': 'Qingyang',
                'scale_w': 9.84,
                'scale_h': 8,
            }, {
                'name': '天水市',
                'name_en': 'Tianshui',
                'scale_w': 10,
                'scale_h': 5.14,
            }, {
                'name': '武威市',
                'name_en': 'Wuwei',
                'scale_w': 6.42,
                'scale_h': 8,
            }, {
                'name': '张掖市',
                'name_en': 'Zhangye',
                'scale_w': 10,
                'scale_h': 4.72,
            },
        ],
    }, {
        'name': '广东省',
        'name_en': 'Guangdong',
        'scale_w': 10,
        'scale_h': 6.94,
        'cities': [
            {
                'name': '潮州市',
                'name_en': 'Chaozhou',
                'scale_w': 8.18,
                'scale_h': 8,
            }, {
                'name': '东莞市',
                'name_en': 'Dongguan',
                'scale_w': 10,
                'scale_h': 6.54,
                'disable_drill_down': True,
            }, {
                'name': '佛山市',
                'name_en': 'Foshan',
                'scale_w': 8.64,
                'scale_h': 8,
            }, {
                'name': '广州市',
                'name_en': 'Guangzhou',
                'scale_w': 6.42,
                'scale_h': 8,
            }, {
                'name': '河源市',
                'name_en': 'Heyuan',
                'scale_w': 6.66,
                'scale_h': 8,
            }, {
                'name': '惠州市',
                'name_en': 'Huizhou',
                'scale_w': 8.44,
                'scale_h': 8,
            }, {
                'name': '江门市',
                'name_en': 'Jiangmen',
                'scale_w': 7.82,
                'scale_h': 8,
            }, {
                'name': '揭阳市',
                'name_en': 'Jieyang',
                'scale_w': 9.28,
                'scale_h': 8,
            }, {
                'name': '茂名市',
                'name_en': 'Maoming',
                'scale_w': 8.14,
                'scale_h': 8,
            }, {
                'name': '梅州市',
                'name_en': 'Meizhou',
                'scale_w': 8.3,
                'scale_h': 8,
            }, {
                'name': '清远市',
                'name_en': 'Qingyuan',
                'scale_w': 9.2,
                'scale_h': 8,
            }, {
                'name': '汕头市',
                'name_en': 'Shantou',
                'scale_w': 10,
                'scale_h': 5.72,
            }, {
                'name': '汕尾市',
                'name_en': 'Shanwei',
                'scale_w': 5.24,
                'scale_h': 8,
            }, {
                'name': '韶关市',
                'name_en': 'Shaoguan',
                'scale_w': 9.32,
                'scale_h': 8,
            }, {
                'name': '深圳市',
                'name_en': 'Shenzhen',
                'scale_w': 10,
                'scale_h': 4.7,
            }, {
                'name': '阳江市',
                'name_en': 'Yangjiang',
                'scale_w': 7.32,
                'scale_h': 8,
            }, {
                'name': '云浮市',
                'name_en': 'Yunfu',
                'scale_w': 10,
                'scale_h': 6.58,
            }, {
                'name': '湛江市',
                'name_en': 'Zhanjiang',
                'scale_w': 6.02,
                'scale_h': 8,
            }, {
                'name': '肇庆市',
                'name_en': 'Zhaoqing',
                'scale_w': 7.54,
                'scale_h': 8,
            }, {
                'name': '中山市',
                'name_en': 'Zhongshan',
                'scale_w': 6.66,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '珠海市',
                'name_en': 'Zhuhai',
                'scale_w': 10,
                'scale_h': 4.98,
            },
        ],
    }, {
        'name': '广西壮族自治区',
        'name_en': 'Guangxi',
        'scale_w': 10,
        'scale_h': 7.22,
        'cities': [
            {
                'name': '百色市',
                'name_en': 'Baise',
                'scale_w': 10,
                'scale_h': 6.54,
            }, {
                'name': '北海市',
                'name_en': 'Beihai',
                'scale_w': 7.24,
                'scale_h': 8,
            }, {
                'name': '崇左市',
                'name_en': 'Chongzuo',
                'scale_w': 7.08,
                'scale_h': 8,
            }, {
                'name': '防城港市',
                'name_en': 'Fangchenggang',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '贵港市',
                'name_en': 'Guigang',
                'scale_w': 8.42,
                'scale_h': 8,
            }, {
                'name': '桂林市',
                'name_en': 'Guilin',
                'scale_w': 7.06,
                'scale_h': 8,
            }, {
                'name': '河池市',
                'name_en': 'Hechi',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '贺州市',
                'name_en': 'Hezhou',
                'scale_w': 7.98,
                'scale_h': 8,
            }, {
                'name': '来宾市',
                'name_en': 'Laibin',
                'scale_w': 10,
                'scale_h': 5.88,
            }, {
                'name': '柳州市',
                'name_en': 'Liuzhou',
                'scale_w': 5.94,
                'scale_h': 8,
            }, {
                'name': '南宁市',
                'name_en': 'Nanning',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '钦州市',
                'name_en': 'Qinzhou',
                'scale_w': 10,
                'scale_h': 6.48,
            }, {
                'name': '梧州市',
                'name_en': 'Wuzhou',
                'scale_w': 5.98,
                'scale_h': 8,
            }, {
                'name': '玉林市',
                'name_en': 'Yulin',
                'scale_w': 7.24,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '贵州省',
        'name_en': 'Guizhou',
        'scale_w': 10,
        'scale_h': 7.7,
        'cities': [
            {
              'name': '安顺市',
              'name_en': 'Anshun',
              'scale_w': 8.28,
              'scale_h': 8,
            }, {
              'name': '毕节市',
              'name_en': 'Bijie',
              'scale_w': 10,
              'scale_h': 4.54,
            }, {
              'name': '贵阳市',
              'name_en': 'Guiyang',
              'scale_w': 7.88,
              'scale_h': 8,
            }, {
              'name': '六盘水市',
              'name_en': 'Liupanshui',
              'scale_w': 7.08,
              'scale_h': 8,
            }, {
              'name': '黔东南苗族侗族自治州',
              'name_en': 'Qiandongnanmiaozudongzu',
              'scale_w': 8.32,
              'scale_h': 8,
            }, {
              'name': '黔南布依族苗族自治州',
              'name_en': 'Qiannanbuyizumiaozu',
              'scale_w': 6.9,
              'scale_h': 8,
            }, {
              'name': '黔西南布依族苗族自治州',
              'name_en': 'Qianxinanbuyizumiaozu',
              'scale_w': 10,
              'scale_h': 7.8,
            }, {
              'name': '铜仁市',
              'name_en': 'Tongren',
              'scale_w': 7,
              'scale_h': 8,
            }, {
              'name': '遵义市',
              'name_en': 'Zunyi',
              'scale_w': 10,
              'scale_h': 8,
            },
        ],
    }, {
        'name': '海南省',
        'name_en': 'Hainan',
        'scale_w': 5.54,
        'scale_h': 8,
        'cities': [
            {
                'name': '白沙黎族自治县',
                'name_en': 'Baishalizu',
                'scale_w': 8.74,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '保亭黎族苗族自治县',
                'name_en': 'Baotinglizumiaozu',
                'scale_w': 7.82,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '昌江黎族自治县',
                'name_en': 'Changjianglizu',
                'scale_w': 7.74,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '澄迈县',
                'name_en': 'Chengmai',
                'scale_w': 7.06,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '儋州市',
                'name_en': 'Danzhou',
                'scale_w': 8.4,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '定安县',
                'name_en': 'Dingan',
                'scale_w': 7.16,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '东方市',
                'name_en': 'Dongfang',
                'scale_w': 7.1,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '海口市',
                'name_en': 'Haikou',
                'scale_w': 8.26,
                'scale_h': 8,
            }, {
                'name': '乐东黎族自治县',
                'name_en': 'Ledonglizu',
                'scale_w': 8.8,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '临高县',
                'name_en': 'Lingao',
                'scale_w': 7.34,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '陵水黎族自治县',
                'name_en': 'Lingshuilizu',
                'scale_w': 7.92,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '琼海市',
                'name_en': 'Qionghai',
                'scale_w': 8.3,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '琼中黎族苗族自治县',
                'name_en': 'Qiongzhonglizuandmiaozu',
                'scale_w': 7.28,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '三亚市',
                'name_en': 'Sanya',
                'scale_w': 10,
                'scale_h': 5.6,
            }, {
                'name': '三沙市',
                'name_en': 'Sansha',
                'scale_w': 4.28,
                'scale_h': 8,
            }, {
                'name': '屯昌县',
                'name_en': 'Tunchang',
                'scale_w': 7.58,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '万宁市',
                'name_en': 'Wanning',
                'scale_w': 8.12,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '文昌市',
                'name_en': 'Wenchang',
                'scale_w': 6.66,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '五指山市',
                'name_en': 'Wuzhishan',
                'scale_w': 7.82,
                'scale_h': 8,
                'disable_drill_down': True,
            },
        ],
    },  {
        'name': '河北省',
        'name_en': 'Hebei',
        'scale_w': 7.82,
        'scale_h': 8,
        'cities': [
            {
                'name': '保定市',
                'name_en': 'Baoding',
                'scale_w': 10,
                'scale_h': 6.7,
            }, {
                'name': '沧州市',
                'name_en': 'Cangzhou',
                'scale_w': 10,
                'scale_h': 6.36,
            }, {
                'name': '承德市',
                'name_en': 'Chengde',
                'scale_w': 10,
                'scale_h': 7.28,
            }, {
                'name': '邯郸市',
                'name_en': 'Handan',
                'scale_w': 10,
                'scale_h': 4.82,
            }, {
                'name': '衡水市',
                'name_en': 'Hengshui',
                'scale_w': 8.5,
                'scale_h': 8,
            }, {
                'name': '廊坊市',
                'name_en': 'Langfang',
                'scale_w': 5.66,
                'scale_h': 8,
            }, {
                'name': '秦皇岛市',
                'name_en': 'Qinhuangdao',
                'scale_w': 8.78,
                'scale_h': 8,
            }, {
                'name': '石家庄市',
                'name_en': 'Shijiazhuang',
                'scale_w': 10,
                'scale_h': 6.78,
            }, {
                'name': '唐山市',
                'name_en': 'Tangshan',
                'scale_w': 9.36,
                'scale_h': 8,
            }, {
                'name': '邢台市',
                'name_en': 'Xingtai',
                'scale_w': 10,
                'scale_h': 5.08,
            }, {
                'name': '张家口市',
                'name_en': 'Zhangjiakou',
                'scale_w': 8.16,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '黑龙江省',
        'name_en': 'Heilongjiang',
        'scale_w': 10,
        'scale_h': 7.3,
        'cities': [
            {
                'name': '大庆市',
                'name_en': 'Daqing',
                'scale_w': 7.84,
                'scale_h': 8,
            }, {
                'name': '大兴安岭地区',
                'name_en': 'Daxinganling',
                'scale_w': 10,
                'scale_h': 4.56,
            }, {
                'name': '哈尔滨市',
                'name_en': 'Haerbin',
                'scale_w': 10,
                'scale_h': 5.74,
            }, {
                'name': '鹤岗市',
                'name_en': 'Hegang',
                'scale_w': 10,
                'scale_h': 4.56,
            }, {
                'name': '黑河市',
                'name_en': 'Heihe',
                'scale_w': 10,
                'scale_h': 7.16,
            }, {
                'name': '佳木斯市',
                'name_en': 'Jiamusi',
                'scale_w': 10,
                'scale_h': 4.52,
            }, {
                'name': '鸡西市',
                'name_en': 'Jixi',
                'scale_w': 10,
                'scale_h': 4.94,
            }, {
                'name': '牡丹江市',
                'name_en': 'Mudanjiang',
                'scale_w': 9.62,
                'scale_h': 8,
            }, {
                'name': '齐齐哈尔市',
                'name_en': 'Qiqihaer',
                'scale_w': 10,
                'scale_h': 6.38,
            }, {
                'name': '七台河市',
                'name_en': 'Qitaihe',
                'scale_w': 10,
                'scale_h': 3.62,
            }, {
                'name': '双鸭山市',
                'name_en': 'Shuangyashan',
                'scale_w': 10,
                'scale_h': 4.86,
            }, {
                'name': '绥化市',
                'name_en': 'Suihua',
                'scale_w': 10,
                'scale_h': 7.06,
            }, {
                'name': '伊春市',
                'name_en': 'Yichun',
                'scale_w': 8.54,
                'scale_h': 8,
            },
        ],
    },  {
        'name': '河南省',
        'name_en': 'Henan',
        'scale_w': 10,
        'scale_h': 8,
        'cities': [
            {
                'name': '安阳市',
                'name_en': 'Anyang',
                'scale_w': 9.36,
                'scale_h': 8,
            }, {
                'name': '鹤壁市',
                'name_en': 'Hebi',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '焦作市',
                'name_en': 'Jiaozuo',
                'scale_w': 10,
                'scale_h': 6.34,
            }, {
                'name': '济源市',
                'name_en': 'Jiyuan',
                'scale_w': 10,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '开封市',
                'name_en': 'Kaifeng',
                'scale_w': 10,
                'scale_h': 6.06,
            }, {
                'name': '漯河市',
                'name_en': 'Luohe',
                'scale_w': 10,
                'scale_h': 6.96,
            }, {
                'name': '洛阳市',
                'name_en': 'Luoyang',
                'scale_w': 9.8,
                'scale_h': 8,
            }, {
                'name': '南阳市',
                'name_en': 'Nanyang',
                'scale_w': 10,
                'scale_h': 5.42,
            }, {
                'name': '平顶山市',
                'name_en': 'Pingdingshan',
                'scale_w': 9.48,
                'scale_h': 8,
            }, {
                'name': '濮阳市',
                'name_en': 'Puyang',
                'scale_w': 10,
                'scale_h': 7.16,
            }, {
                'name': '三门峡市',
                'name_en': 'Sanmenxia',
                'scale_w': 8.72,
                'scale_h': 8,
            }, {
                'name': '商丘市',
                'name_en': 'Shangqiu',
                'scale_w': 10,
                'scale_h': 6.36,
            }, {
                'name': '新乡市',
                'name_en': 'Xinxiang',
                'scale_w': 10,
                'scale_h': 5.86,
            }, {
                'name': '信阳市',
                'name_en': 'Xinyang',
                'scale_w': 10,
                'scale_h': 5.74,
            }, {
                'name': '许昌市',
                'name_en': 'Xuchang',
                'scale_w': 10,
                'scale_h': 5.7,
            }, {
                'name': '郑州市',
                'name_en': 'Zhengzhou',
                'scale_w': 10,
                'scale_h': 4.84,
            }, {
                'name': '周口市',
                'name_en': 'Zhoukou',
                'scale_w': 9.82,
                'scale_h': 8,
            }, {
                'name': '驻马店市',
                'name_en': 'Zhumadian',
                'scale_w': 10,
                'scale_h': 5.94,
            },
        ],
    }, {
        'name': '香港特别行政区',
        'name_en': 'HongKong',
        'scale_w': 10,
        'scale_h': 6.78,
        'disable_drill_down': True,
        'cities': [
            {
                'name': '香港特别行政区',
                'name_en': 'HongKong',
                'scale_w': 10,
                'scale_h': 6.78,
                'disable_drill_down': True,
            },
        ],
    }, {
        'name': '湖北省',
        'name_en': 'Hubei',
        'scale_w': 10,
        'scale_h': 5.46,
        'cities': [
            {
                'name': '恩施土家族苗族自治州',
                'name_en': 'Enshitujiazumiaozu',
                'scale_w': 7.98,
                'scale_h': 8,
            }, {
                'name': '鄂州市',
                'name_en': 'Ezhou',
                'scale_w': 7.86,
                'scale_h': 8,
            }, {
                'name': '黄冈市',
                'name_en': 'Huanggang',
                'scale_w': 7.38,
                'scale_h': 8,
            }, {
                'name': '黄石市',
                'name_en': 'Huangshi',
                'scale_w': 9.56,
                'scale_h': 8,
            }, {
                'name': '荆门市',
                'name_en': 'Jingmen',
                'scale_w': 10,
                'scale_h': 7.48,
            }, {
                'name': '荆州市',
                'name_en': 'Jingzhou',
                'scale_w': 10,
                'scale_h': 4.36,
            }, {
                'name': '潜江市',
                'name_en': 'Qianjiang',
                'scale_w': 7.08,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '神农架林区',
                'name_en': 'Shennongjialin',
                'scale_w': 10,
                'scale_h': 7.28,
                'disable_drill_down': True,
            }, {
                'name': '十堰市',
                'name_en': 'Shiyan',
                'scale_w': 9.72,
                'scale_h': 8,
            }, {
                'name': '随州市',
                'name_en': 'Suizhou',
                'scale_w': 10,
                'scale_h': 7.88,
            }, {
                'name': '天门市',
                'name_en': 'Tianmen',
                'scale_w': 9.62,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '武汉市',
                'name_en': 'Wuhan',
                'scale_w': 7.94,
                'scale_h': 8,
            }, {
                'name': '襄阳市',
                'name_en': 'Xiangyang',
                'scale_w': 10,
                'scale_h': 5.96,
            }, {
                'name': '咸宁市',
                'name_en': 'Xianning',
                'scale_w': 9.06,
                'scale_h': 8,
            }, {
                'name': '仙桃市',
                'name_en': 'Xiantao',
                'scale_w': 10,
                'scale_h': 7.5,
                'disable_drill_down': True,
            }, {
                'name': '孝感市',
                'name_en': 'Xiaogan',
                'scale_w': 6.94,
                'scale_h': 8,
            }, {
                'name': '宜昌市',
                'name_en': 'Yichang',
                'scale_w': 8.94,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '湖南省',
        'name_en': 'Hunan',
        'scale_w': 7.98,
        'scale_h': 8,
        'cities': [
            {
                'name': '常德市',
                'name_en': 'Changde',
                'scale_w': 8.44,
                'scale_h': 8,
            }, {
                'name': '长沙市',
                'name_en': 'Changsha',
                'scale_w': 10,
                'scale_h': 3.44,
            }, {
                'name': '郴州市',
                'name_en': 'Chenzhou',
                'scale_w': 8.26,
                'scale_h': 8,
            }, {
                'name': '衡阳市',
                'name_en': 'Hengyang',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '怀化市',
                'name_en': 'Huaihua',
                'scale_w': 5.88,
                'scale_h': 8,
            }, {
                'name': '娄底市',
                'name_en': 'Loudi',
                'scale_w': 10,
                'scale_h': 5.92,
            }, {
                'name': '邵阳市',
                'name_en': 'Shaoyang',
                'scale_w': 10,
                'scale_h': 7.5,
            }, {
                'name': '湘潭市',
                'name_en': 'Xiangtan',
                'scale_w': 10,
                'scale_h': 6.76,
            }, {
                'name': '湘西土家族苗族自治州',
                'name_en': 'Xiangxitujiazumiaozu',
                'scale_w': 5.1,
                'scale_h': 8,
            }, {
                'name': '益阳市',
                'name_en': 'Yiyang',
                'scale_w': 10,
                'scale_h': 6.98,
            }, {
                'name': '永州市',
                'name_en': 'Yongzhou',
                'scale_w': 5.42,
                'scale_h': 8,
            }, {
                'name': '岳阳市',
                'name_en': 'Yueyang',
                'scale_w': 10,
                'scale_h': 7.74,
            }, {
                'name': '张家界市',
                'name_en': 'Zhangjiajie',
                'scale_w': 10,
                'scale_h': 5.56,
            }, {
                'name': '株洲市',
                'name_en': 'Zhuzhou',
                'scale_w': 4.62,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '江苏省',
        'name_en': 'Jiangsu',
        'scale_w': 10,
        'scale_h': 7.8,
        'cities': [
            {
                'name': '常州市',
                'name_en': 'Changzhou',
                'scale_w': 9.4,
                'scale_h': 8,
            }, {
                'name': '淮安市',
                'name_en': 'Huaian',
                'scale_w': 8.4,
                'scale_h': 8,
            }, {
                'name': '连云港市',
                'name_en': 'Lianyungang',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '南京市',
                'name_en': 'Nanjing',
                'scale_w': 5.12,
                'scale_h': 8,
            }, {
                'name': '南通市',
                'name_en': 'Nantong',
                'scale_w': 10,
                'scale_h': 6.14,
            }, {
                'name': '宿迁市',
                'name_en': 'Suqian',
                'scale_w': 7.7,
                'scale_h': 8,
            }, {
                'name': '苏州市',
                'name_en': 'Suzhou',
                'scale_w': 9.12,
                'scale_h': 8,
            }, {
                'name': '泰州市',
                'name_en': 'Taizhou',
                'scale_w': 5.7,
                'scale_h': 8,
            }, {
                'name': '无锡市',
                'name_en': 'Wuxi',
                'scale_w': 9.76,
                'scale_h': 8,
            }, {
                'name': '徐州市',
                'name_en': 'Xuzhou',
                'scale_w': 10,
                'scale_h': 5.44,
            }, {
                'name': '盐城市',
                'name_en': 'Yancheng',
                'scale_w': 6.44,
                'scale_h': 8,
            }, {
                'name': '扬州市',
                'name_en': 'Yangzhou',
                'scale_w': 6.04,
                'scale_h': 8,
            }, {
                'name': '镇江市',
                'name_en': 'Zhenjiang',
                'scale_w': 10,
                'scale_h': 6.9,
            },
        ],
    }, {
        'name': '江西省',
        'name_en': 'Jiangxi',
        'scale_w': 7.04,
        'scale_h': 8,
        'cities': [
            {
                'name': '抚州市',
                'name_en': 'Fuzhou',
                'scale_w': 6.88,
                'scale_h': 8,
            }, {
                'name': '赣州市',
                'name_en': 'Ganzhou',
                'scale_w': 8.24,
                'scale_h': 8,
            }, {
                'name': '吉安市',
                'name_en': 'Jian',
                'scale_w': 8.46,
                'scale_h': 8,
            }, {
                'name': '景德镇市',
                'name_en': 'Jingdezhen',
                'scale_w': 4.98,
                'scale_h': 8,
            }, {
                'name': '九江市',
                'name_en': 'Jiujiang',
                'scale_w': 10,
                'scale_h': 4.7,
            }, {
                'name': '南昌市',
                'name_en': 'Nanchang',
                'scale_w': 9.34,
                'scale_h': 8,
            }, {
                'name': '萍乡市',
                'name_en': 'Pingxiang',
                'scale_w': 5.36,
                'scale_h': 8,
            }, {
                'name': '上饶市',
                'name_en': 'Shangrao',
                'scale_w': 9.52,
                'scale_h': 8,
            }, {
                'name': '新余市',
                'name_en': 'Xinyu',
                'scale_w': 10,
                'scale_h': 6.26,
            }, {
                'name': '宜春市',
                'name_en': 'Yichun',
                'scale_w': 10,
                'scale_h': 6.9,
            }, {
                'name': '鹰潭市',
                'name_en': 'Yingtan',
                'scale_w': 8,
                'scale_h': 8,
            },
          ],
      }, {
          'name': '吉林省',
          'name_en': 'Jilin',
          'scale_w': 10,
          'scale_h': 5.64,
          'cities': [
              {
                  'name': '白城市',
                  'name_en': 'Baicheng',
                  'scale_w': 10,
                  'scale_h': 7.6,
              }, {
                  'name': '白山市',
                  'name_en': 'Baishan',
                  'scale_w': 10,
                  'scale_h': 6.74,
              }, {
                  'name': '长春市',
                  'name_en': 'Changchun',
                  'scale_w': 10,
                  'scale_h': 6.8,
              }, {
                  'name': '吉林市',
                  'name_en': 'Jilin',
                  'scale_w': 8.74,
                  'scale_h': 8,
              }, {
                  'name': '辽源市',
                  'name_en': 'Liaoyuan',
                  'scale_w': 8.62,
                  'scale_h': 8,
              }, {
                  'name': '四平市',
                  'name_en': 'Siping',
                  'scale_w': 10,
                  'scale_h': 5.2,
              }, {
                  'name': '松原市',
                  'name_en': 'Songyuan',
                  'scale_w': 10,
                  'scale_h': 5.06,
              }, {
                  'name': '通化市',
                  'name_en': 'Tonghua',
                  'scale_w': 5.54,
                  'scale_h': 8,
              }, {
                  'name': '延边朝鲜族自治州',
                  'name_en': 'Yanbianchaoxianzu',
                  'scale_w': 10,
                  'scale_h': 6.54,
              },
          ],
      }, {
          'name': '辽宁省',
          'name_en': 'Liaoning',
          'scale_w': 10,
          'scale_h': 6.88,
          'cities': [
              {
                  'name': '鞍山市',
                  'name_en': 'Anshan',
                  'scale_w': 8.06,
                  'scale_h': 8,
              }, {
                  'name': '本溪市',
                  'name_en': 'Benxi',
                  'scale_w': 10,
                  'scale_h': 3.42,
              }, {
                  'name': '朝阳市',
                  'name_en': 'Chaoyang',
                  'scale_w': 10,
                  'scale_h': 7.3,
              }, {
                  'name': '大连市',
                  'name_en': 'Dalian',
                  'scale_w': 10,
                  'scale_h': 5.84,
              }, {
                  'name': '丹东市',
                  'name_en': 'Dandong',
                  'scale_w': 10,
                  'scale_h': 6.08,
              }, {
                  'name': '抚顺市',
                  'name_en': 'Fushun',
                  'scale_w': 10,
                  'scale_h': 6.78,
              }, {
                  'name': '阜新市',
                  'name_en': 'Fuxin',
                  'scale_w': 10,
                  'scale_h': 5.92,
              }, {
                  'name': '葫芦岛市',
                  'name_en': 'Huludao',
                  'scale_w': 10,
                  'scale_h': 6.64,
              }, {
                  'name': '锦州市',
                  'name_en': 'Jinzhou',
                  'scale_w': 10,
                  'scale_h': 7.14,
              }, {
                  'name': '辽阳市',
                  'name_en': 'Liaoyang',
                  'scale_w': 6.04,
                  'scale_h': 8,
              }, {
                  'name': '盘锦市',
                  'name_en': 'Panjin',
                  'scale_w': 9.34,
                  'scale_h': 8,
              }, {
                  'name': '沈阳市',
                  'name_en': 'Shenyang',
                  'scale_w': 6.04,
                  'scale_h': 8,
              }, {
                  'name': '铁岭市',
                  'name_en': 'Tieling',
                  'scale_w': 8.86,
                  'scale_h': 8,
              }, {
                  'name': '营口市',
                  'name_en': 'Yingkou',
                  'scale_w': 8.22,
                  'scale_h': 8,
              },
          ],
      }, {
        'name': '澳门特别行政区',
        'name_en': 'Macao',
        'scale_w': 5.2,
        'scale_h': 8,
        'disable_drill_down': True,
        'cities': [
            {
                'name': '澳门特别行政区',
                'name_en': 'Macao',
                'scale_w': 5.2,
                'scale_h': 8,
                'disable_drill_down': True,
            },
        ],
      }, {
        'name': '内蒙古自治区',
        'name_en': 'Neimenggu',
        'scale_w': 10,
        'scale_h': 5.22,
        'cities': [
            {
                'name': '阿拉善盟',
                'name_en': 'Alashan',
                'scale_w': 10,
                'scale_h': 5.58,
            }, {
                'name': '包头市',
                'name_en': 'Baotou',
                'scale_w': 7.06,
                'scale_h': 8,
            }, {
                'name': '巴彦淖尔市',
                'name_en': 'Bayannaoer',
                'scale_w': 10,
                'scale_h': 4.9,
            }, {
                'name': '赤峰市',
                'name_en': 'Chifeng',
                'scale_w': 9.36,
                'scale_h': 8,
            }, {
                'name': '鄂尔多斯市',
                'name_en': 'Eerduosi',
                'scale_w': 10,
                'scale_h': 6.56,
            }, {
                'name': '呼和浩特市',
                'name_en': 'Huhehaote',
                'scale_w': 7.98,
                'scale_h': 8,
            }, {
                'name': '呼伦贝尔市',
                'name_en': 'Hulunbeier',
                'scale_w': 10,
                'scale_h': 5.94,
            }, {
                'name': '通辽市',
                'name_en': 'Tongliao',
                'scale_w': 10,
                'scale_h': 7.64,
            }, {
                'name': '乌海市',
                'name_en': 'Wuhai',
                'scale_w': 4.86,
                'scale_h': 8,
            }, {
                'name': '乌兰察布市',
                'name_en': 'Wulanchabu',
                'scale_w': 10,
                'scale_h': 7.2,
            }, {
                'name': '锡林郭勒盟',
                'name_en': 'Xilinguole',
                'scale_w': 10,
                'scale_h': 5.9,
            }, {
                'name': '兴安盟',
                'name_en': 'Xingan',
                'scale_w': 9.78,
                'scale_h': 8,
            },
        ] ,
    }, {
        'name': '宁夏回族自治区',
        'name_en': 'Ningxia',
        'scale_w': 6.52,
        'scale_h': 8,
        'cities': [
            {
                'name': '固原市',
                'name_en': 'Guyuan',
                'scale_w': 10,
                'scale_h': 7.86,
            }, {
                'name': '石嘴山市',
                'name_en': 'Shizuishan',
                'scale_w': 10,
                'scale_h': 7.86,
            }, {
                'name': '吴忠市',
                'name_en': 'Wuzhong',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '银川市',
                'name_en': 'Yinchuan',
                'scale_w': 6.64,
                'scale_h': 8,
            }, {
                'name': '中卫市',
                'name_en': 'Zhongwei',
                'scale_w': 10,
                'scale_h': 7.44,
            },
        ],
    }, {
        'name': '青海省',
        'name_en': 'Qinghai',
        'scale_w': 10,
        'scale_h': 5.58,
        'cities': [
            {
                'name': '果洛藏族自治州',
                'name_en': 'Guoluozangzu',
                'scale_w': 10,
                'scale_h': 6.4,
            }, {
                'name': '海北藏族自治州',
                'name_en': 'Haibeizangzu',
                'scale_w': 10,
                'scale_h': 5.16,
            }, {
                'name': '海东市',
                'name_en': 'Haidong',
                'scale_w': 6.66,
                'scale_h': 8,
            }, {
                'name': '海南藏族自治州',
                'name_en': 'Hainanzangzu',
                'scale_w': 9.02,
                'scale_h': 8,
            }, {
                'name': '海西蒙古族藏族自治州',
                'name_en': 'Haiximengguzuzangzu',
                'scale_w': 10,
                'scale_h': 6.46,
            }, {
                'name': '黄南藏族自治州',
                'name_en': 'Huangnanzangzu',
                'scale_w': 6.74,
                'scale_h': 8,
            }, {
                'name': '西宁市',
                'name_en': 'Xining',
                'scale_w': 6.76,
                'scale_h': 8,
            }, {
                'name': '玉树藏族自治州',
                'name_en': 'Yushuzangzu',
                'scale_w': 10,
                'scale_h': 5.62,
            },
        ],
    }, {
        'name': '陕西省',
        'name_en': 'Shaanxi',
        'scale_w': 5.64,
        'scale_h': 8,
        'cities': [
            {
                'name': '安康市',
                'name_en': 'Ankang',
                'scale_w': 8.2,
                'scale_h': 8,
            }, {
                'name': '宝鸡市',
                'name_en': 'Baoji',
                'scale_w': 9.16,
                'scale_h': 8,
            }, {
                'name': '汉中市',
                'name_en': 'Hanzhong',
                'scale_w': 10,
                'scale_h': 6.22,
            }, {
                'name': '商洛市',
                'name_en': 'Shangluo',
                'scale_w': 10,
                'scale_h': 5.44,
            }, {
                'name': '铜川市',
                'name_en': 'Tongchuan',
                'scale_w': 9.42,
                'scale_h': 8,
            }, {
                'name': '渭南市',
                'name_en': 'Weinan',
                'scale_w': 7.96,
                'scale_h': 8,
            }, {
                'name': '西安市',
                'name_en': 'Xian',
                'scale_w': 10,
                'scale_h': 4.86,
            }, {
                'name': '咸阳市',
                'name_en': 'Xianyang',
                'scale_w': 9.08,
                'scale_h': 8,
            }, {
                'name': '延安市',
                'name_en': 'Yanan',
                'scale_w': 10,
                'scale_h': 7.46,
            }, {
                'name': '榆林市',
                'name_en': 'Yulin',
                'scale_w': 10,
                'scale_h': 6.94,
            },
        ],
    }, {
        'name': '山东省',
        'name_en': 'Shandong',
        'scale_w': 10,
        'scale_h': 5.1,
        'cities': [
            {
                'name': '滨州市',
                'name_en': 'Binzhou',
                'scale_w': 5.72,
                'scale_h': 8,
            }, {
                'name': '德州市',
                'name_en': 'Dezhou',
                'scale_w': 9.22,
                'scale_h': 8,
            }, {
                'name': '东营市',
                'name_en': 'Dongying',
                'scale_w': 7.9,
                'scale_h': 8,
            }, {
                'name': '菏泽市',
                'name_en': 'Heze',
                'scale_w': 9.7,
                'scale_h': 8,
            }, {
                'name': '济南市',
                'name_en': 'Jinan',
                'scale_w': 9.06,
                'scale_h': 8,
            }, {
                'name': '济宁市',
                'name_en': 'Jining',
                'scale_w': 8.98,
                'scale_h': 8,
            }, {
                'name': '聊城市',
                'name_en': 'Liaocheng',
                'scale_w': 8.1,
                'scale_h': 8,
            }, {
                'name': '临沂市',
                'name_en': 'Linyi',
                'scale_w': 7.8,
                'scale_h': 8,
            }, {
                'name': '青岛市',
                'name_en': 'Qingdao',
                'scale_w': 7.5,
                'scale_h': 8,
            }, {
                'name': '日照市',
                'name_en': 'Rizhao',
                'scale_w': 8.88,
                'scale_h': 8,
            }, {
                'name': '泰安市',
                'name_en': 'Taian',
                'scale_w': 10,
                'scale_h': 4.32,
            }, {
                'name': '潍坊市',
                'name_en': 'Weifang',
                'scale_w': 9.28,
                'scale_h': 8,
            }, {
                'name': '威海市',
                'name_en': 'Weihai',
                'scale_w': 10,
                'scale_h': 5.54,
            }, {
                'name': '烟台市',
                'name_en': 'Yantai',
                'scale_w': 10,
                'scale_h': 7.7,
            }, {
                'name': '枣庄市',
                'name_en': 'Zaozhuang',
                'scale_w': 9.56,
                'scale_h': 8,
            }, {
                'name': '淄博市',
                'name_en': 'Zibo',
                'scale_w': 5.74,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '上海市',
        'name_en': 'Shanghai',
        'scale_w': 8.56,
        'scale_h': 8,
        'cities': [
            {
                'name': '上海市',
                'name_en': 'Shanghai',
                'scale_w': 8.56,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '山西省',
        'name_en': 'Shanxi',
        'scale_w': 5.64,
        'scale_h': 8,
        'cities': [
            {
                'name': '长治市',
                'name_en': 'Changzhi',
                'scale_w': 10,
                'scale_h': 7.4,
            }, {
                'name': '大同市',
                'name_en': 'Datong',
                'scale_w': 9.38,
                'scale_h': 8,
            }, {
                'name': '怀仁市',
                'name_en': 'Huairen',
                'scale_w': 9.38,
                'scale_h': 8,
            }, {
                'name': '晋城市',
                'name_en': 'Jincheng',
                'scale_w': 10,
                'scale_h': 5.24,
            }, {
                'name': '晋中市',
                'name_en': 'Jinzhong',
                'scale_w': 10,
                'scale_h': 5.32,
            }, {
                'name': '临汾市',
                'name_en': 'Linfen',
                'scale_w': 10,
                'scale_h': 7.1,
            }, {
                'name': '吕梁市',
                'name_en': 'lüliang',
                'scale_w': 7.84,
                'scale_h': 8,
            }, {
                'name': '朔州市',
                'name_en': 'Shuozhou',
                'scale_w': 10,
                'scale_h': 7.26,
            }, {
                'name': '太原市',
                'name_en': 'Taiyuan',
                'scale_w': 10,
                'scale_h': 5.88,
            }, {
                'name': '忻州市',
                'name_en': 'Xinzhou',
                'scale_w': 10,
                'scale_h': 5.06,
            }, {
                'name': '阳泉市',
                'name_en': 'Yangquan',
                'scale_w': 10,
                'scale_h': 7.72,
            }, {
                'name': '运城市',
                'name_en': 'Yuncheng',
                'scale_w': 10,
                'scale_h': 6.72,
            },
        ],
    }, {
        'name': '四川省',
        'name_en': 'Sichuan',
        'scale_w': 10,
        'scale_h': 7.4,
        'cities': [
            {
                'name': '阿坝藏族羌族自治州',
                'name_en': 'Abazangzuqiangzu',
                'scale_w': 8.56,
                'scale_h': 8,
            }, {
                'name': '巴中市',
                'name_en': 'Bazhong',
                'scale_w': 7.52,
                'scale_h': 8,
            }, {
                'name': '成都市',
                'name_en': 'Chengdu',
                'scale_w': 10,
                'scale_h': 7.08,
            }, {
                'name': '达州市',
                'name_en': 'Dazhou',
                'scale_w': 7.48,
                'scale_h': 8,
            }, {
                'name': '德阳市',
                'name_en': 'Deyang',
                'scale_w': 9.42,
                'scale_h': 8,
            }, {
                'name': '甘孜藏族自治州',
                'name_en': 'Ganzizangzu',
                'scale_w': 6.6,
                'scale_h': 8,
            }, {
                'name': '广安市',
                'name_en': 'Guangan',
                'scale_w': 10,
                'scale_h': 6.08,
            }, {
                'name': '广元市',
                'name_en': 'Guangyuan',
                'scale_w': 10,
                'scale_h': 6.52,
            }, {
                'name': '乐山市',
                'name_en': 'Leshan',
                'scale_w': 7.14,
                'scale_h': 8,
            }, {
                'name': '凉山彝族自治州',
                'name_en': 'Liangshanyizu',
                'scale_w': 9.38,
                'scale_h': 8,
            }, {
                'name': '泸州市',
                'name_en': 'Luzhou',
                'scale_w': 5.92,
                'scale_h': 8,
            }, {
                'name': '眉山市',
                'name_en': 'Meishan',
                'scale_w': 10,
                'scale_h': 5.8,
            }, {
                'name': '绵阳市',
                'name_en': 'Mianyang',
                'scale_w': 6.78,
                'scale_h': 8,
            }, {
                'name': '南充市',
                'name_en': 'Nanchong',
                'scale_w': 8.74,
                'scale_h': 8,
            }, {
                'name': '内江市',
                'name_en': 'Neijiang',
                'scale_w': 10,
                'scale_h': 7.26,
            }, {
                'name': '攀枝花市',
                'name_en': 'Panzhihua',
                'scale_w': 7.08,
                'scale_h': 8,
            }, {
                'name': '遂宁市',
                'name_en': 'Suining',
                'scale_w': 7.6,
                'scale_h': 8,
            }, {
                'name': '雅安市',
                'name_en': 'Yaan',
                'scale_w': 5.58,
                'scale_h': 8,
            }, {
                'name': '宜宾市',
                'name_en': 'Yibin',
                'scale_w': 9.78,
                'scale_h': 8,
            }, {
                'name': '自贡市',
                'name_en': 'Zigong',
                'scale_w': 10,
                'scale_h': 5.88,
            }, {
                'name': '资阳市',
                'name_en': 'Ziyang',
                'scale_w': 10,
                'scale_h': 7.26,
            },
        ],
    }, {
        'name': '台湾省',
        'name_en': 'Taiwan',
        'scale_w': 10,
        'scale_h': 7.68,
        'disable_drill_down': True,
        'cities': [
            {
                'name': '台湾省',
                'name_en': 'Taiwan',
                'scale_w': 10,
                'scale_h': 7.68,
                'disable_drill_down': True,
            },
        ],
    }, {
        'name': '天津市',
        'name_en': 'Tianjin',
        'scale_w': 6.4,
        'scale_h': 8,
        'cities': [
            {
                'name': '天津市',
                'name_en': 'Tianjin',
                'scale_w': 6.4,
                'scale_h': 8,
            },
        ],
    }, {
        'name': '新疆维吾尔自治区',
        'name_en': 'Xinjiang',
        'scale_w': 10,
        'scale_h': 6.5,
        'cities': [
            {
                'name': '阿克苏地区',
                'name_en': 'Akesu',
                'scale_w': 10,
                'scale_h': 5.26,
            }, {
                'name': '阿拉尔市',
                'name_en': 'Alaer',
                'scale_w': 10,
                'scale_h': 6.2,
                'disable_drill_down': True,
            }, {
                'name': '阿勒泰地区',
                'name_en': 'Aletai',
                'scale_w': 10,
                'scale_h': 7.56,
            }, {
                'name': '巴音郭楞蒙古自治州',
                'name_en': 'Bayinguolengmenggu',
                'scale_w': 10,
                'scale_h': 7,
            }, {
                'name': '北屯市',
                'name_en': 'Beitun',
                'scale_w': 10,
                'scale_h': 6.42,
                'disable_drill_down': True,
            }, {
                'name': '博尔塔拉蒙古自治州',
                'name_en': 'Boertalamenggu',
                'scale_w': 10,
                'scale_h': 3.54,
            }, {
                'name': '昌吉回族自治州',
                'name_en': 'Changjihuizu',
                'scale_w': 10,
                'scale_h': 4,
            }, {
                'name': '哈密市',
                'name_en': 'Hami',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '和田地区',
                'name_en': 'Hetian',
                'scale_w': 10,
                'scale_h': 6.98,
            }, {
                'name': '胡杨河市',
                'name_en': 'Huyanghe',
                'scale_w': 6.04,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '喀什地区',
                'name_en': 'Kashi',
                'scale_w': 9,
                'scale_h': 8,
            }, {
                'name': '可克达拉市',
                'name_en': 'Kekedala',
                'scale_w': 7.98,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '克拉玛依市',
                'name_en': 'Kelamayi',
                'scale_w': 5.56,
                'scale_h': 8,
            }, {
                'name': '克孜勒苏柯尔克孜自治州',
                'name_en': 'Kezilesukeerkezi',
                'scale_w': 10,
                'scale_h': 7,
            }, {
                'name': '昆玉市',
                'name_en': 'Kunyu',
                'scale_w': 10,
                'scale_h': 7.94,
                'disable_drill_down': True,
            }, {
                'name': '石河子市',
                'name_en': 'Shihezi',
                'scale_w': 6.34,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '双河市',
                'name_en': 'Shuanghe',
                'scale_w': 9.8,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '塔城地区',
                'name_en': 'Tacheng',
                'scale_w': 10,
                'scale_h': 7.42,
            }, {
                'name': '铁门关市',
                'name_en': 'Tiemenguan',
                'scale_w': 7.08,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '吐鲁番市',
                'name_en': 'Tulufan',
                'scale_w': 10,
                'scale_h': 5.24,
            }, {
                'name': '图木舒克市',
                'name_en': 'Tumushuke',
                'scale_w': 10,
                'scale_h': 7.72,
                'disable_drill_down': True,
            }, {
                'name': '五家渠市',
                'name_en': 'Wujiaqu',
                'scale_w': 4.74,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '乌鲁木齐市',
                'name_en': 'Wulumuqi',
                'scale_w': 8.4,
                'scale_h': 8,
            }, {
                'name': '新星市',
                'name_en': 'Xinxing',
                'scale_w': 9.74,
                'scale_h': 8,
                'disable_drill_down': True,
            }, {
                'name': '伊犁哈萨克自治州',
                'name_en': 'Yilihasake',
                'scale_w': 10,
                'scale_h': 5.08,
            },
        ],
    }, {
        'name': '西藏自治区',
        'name_en': 'Xizang',
        'scale_w': 10,
        'scale_h': 4.66,
        'cities': [
            {
                'name': '阿里地区',
                'name_en': 'Ali',
                'scale_w': 10,
                'scale_h': 7.8,
            }, {
                'name': '昌都市',
                'name_en': 'Changdu',
                'scale_w': 10,
                'scale_h': 7.52,
            }, {
                'name': '拉萨市',
                'name_en': 'Lasa',
                'scale_w': 10,
                'scale_h': 6.36,
            }, {
                'name': '林芝市',
                'name_en': 'Linzhi',
                'scale_w': 10,
                'scale_h': 4.72,
            }, {
                'name': '那曲市',
                'name_en': 'Naqu',
                'scale_w': 10,
                'scale_h': 6.56,
            }, {
                'name': '日喀则市',
                'name_en': 'Rikaze',
                'scale_w': 10,
                'scale_h': 5.62,
            }, {
                'name': '山南市',
                'name_en': 'Shannan',
                'scale_w': 10,
                'scale_h': 6.94,
            },
        ],
    }, {
        'name': '云南省',
        'name_en': 'Yunnan',
        'scale_w': 8.6,
        'scale_h': 8,
        'cities': [
            {
                'name': '保山市',
                'name_en': 'Baoshan',
                'scale_w': 9.04,
                'scale_h': 8,
            }, {
                'name': '楚雄彝族自治州',
                'name_en': 'Chuxiongyizu',
                'scale_w': 6.2,
                'scale_h': 8,
            }, {
                'name': '大理白族自治州',
                'name_en': 'Dalibaizu',
                'scale_w': 8.58,
                'scale_h': 8,
            }, {
                'name': '德宏傣族景颇族自治州',
                'name_en': 'Dehongdaizujingpozu',
                'scale_w': 6.46,
                'scale_h': 8,
            }, {
                'name': '迪庆藏族自治州',
                'name_en': 'Diqingzangzu',
                'scale_w': 5.82,
                'scale_h': 8,
            }, {
                'name': '红河哈尼族彝族自治州',
                'name_en': 'Honghehanizuyizu',
                'scale_w': 8.56,
                'scale_h': 8,
            }, {
                'name': '昆明市',
                'name_en': 'Kunming',
                'scale_w': 5.58,
                'scale_h': 8,
            }, {
                'name': '丽江市',
                'name_en': 'Lijiang',
                'scale_w': 8.8,
                'scale_h': 8,
            }, {
                'name': '临沧市',
                'name_en': 'Lincang',
                'scale_w': 7.68,
                'scale_h': 8,
            }, {
                'name': '怒江傈僳族自治州',
                'name_en': 'Nujianglisuzu',
                'scale_w': 4.26,
                'scale_h': 8,
            }, {
                'name': '普洱市',
                'name_en': 'Puer',
                'scale_w': 9.06,
                'scale_h': 8,
            }, {
                'name': '曲靖市',
                'name_en': 'Qujing',
                'scale_w': 5.24,
                'scale_h': 8,
            }, {
                'name': '文山壮族苗族自治州',
                'name_en': 'Wenshanzhuangzumiaozu',
                'scale_w': 10,
                'scale_h': 6.84,
            }, {
                'name': '西双版纳傣族自治州',
                'name_en': 'Xishuangbannadaizu',
                'scale_w': 10,
                'scale_h': 7.7,
            }, {
                'name': '玉溪市',
                'name_en': 'Yuxi',
                'scale_w': 9.18,
                'scale_h': 8,
            }, {
                'name': '昭通市',
                'name_en': 'Zhaotong',
                'scale_w': 9.16,
                'scale_h': 8,
            }
        ],
    }, {
        'name': '浙江省',
        'name_en': 'Zhejiang',
        'scale_w': 9.54,
        'scale_h': 8,
        'cities': [
            {
                'name': '杭州市',
                'name_en': 'Hangzhou',
                'scale_w': 10,
                'scale_h': 5.8,
            }, {
                'name': '湖州市',
                'name_en': 'Huzhou',
                'scale_w': 10,
                'scale_h': 6.46,
            }, {
                'name': '嘉兴市',
                'name_en': 'Jiaxing',
                'scale_w': 10,
                'scale_h': 7.88,
            }, {
                'name': '金华市',
                'name_en': 'Jinhua',
                'scale_w': 10,
                'scale_h': 7.46,
            }, {
                'name': '丽水市',
                'name_en': 'Lishui',
                'scale_w': 9.08,
                'scale_h': 8,
            }, {
                'name': '宁波市',
                'name_en': 'Ningbo',
                'scale_w': 7.02,
                'scale_h': 8,
            }, {
                'name': '衢州市',
                'name_en': 'Quzhou',
                'scale_w': 8.38,
                'scale_h': 8,
            }, {
                'name': '绍兴市',
                'name_en': 'Shaoxing',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '台州市',
                'name_en': 'Taizhou',
                'scale_w': 10,
                'scale_h': 8,
            }, {
                'name': '温州市',
                'name_en': 'Wenzhou',
                'scale_w': 8.9,
                'scale_h': 8,
            }, {
                'name': '舟山市',
                'name_en': 'Zhoushan',
                'scale_w': 7.8,
                'scale_h': 8,
            }
        ]
    },
]
